# Site information
site_name: AI for Business
site_author: Alonso Astroza & Loreto Bravo
site_description: >-
  IDS UDD's AI for business course


# Repository
repo_name: idsudd/ai-for-business
repo_url: https://github.com/idsudd/ai-for-business


# Configuration
theme:
  name: material
  language: es
  icon:
    logo: material/book-heart-outline
  palette:
    - scheme: default
      primary: white
  font:
    text: Inter
    code: Source Code Pro
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.sections
    - announce.dismiss
    - content.tabs.link

# Copyright
copyright: Copyright &copy; 2024 Instituto de Data Science, Facultad de Ingeniería, Universidad del Desarrollo.

# Additional configuration
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:alonsoastroza@udd.cl

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - section-index
  - social:
      cards_layout_options:
        color: #173a58
  
nav:
  - Home: index.md
  - Comenzando:
      - Bienvenida: welcome.md
      - Bibliografía: bibliography.md
  - Clases:
      - lectures/index.md
  - Material:
    - material/index.md
    - ¿Qué es la Inteligencia Artificial?:
      - Definicion: material/what-is-ai.md
      - Historia: material/history.md
    - Inteligencia Artificial Generativa:
      - Introducción: material/generative-ai.md
      - Principios: material/generative-ai-principles.md
      - Aplicaciones:
        - En el trabajo: material/generative-ai-applications-work.md
        - En la creatividad: material/generative-ai-applications-creativity.md
        - En la eduación: material/generative-ai-applications-education.md
        - En el futuro: material/generative-ai-applications-future.md
      - Cómo funciona ChatGPT:
        - Large Language Models: material/large-language-models.md
        - Reinforcement Learning from Human Feedback: material/RLHF.md
        - Limitaciones: material/limitations.md
        - Evaluacion: material/evaluation.md
  - Recetas:
    - cookbook/index.md
    - Diálogos efectivos con un LLM:
      - Prompts: cookbook/prompts.md
      - Ingeniería de prompts: cookbook/prompt-engineering.md
      - Prompts adversos: cookbook/adversarial-prompts.md
    - Copilotos:
      - Microsoft: cookbook/microsoft.md
      - GitHub: cookbook/github.md
    - Creación de contenido:
      - Imagenes: cookbook/images.md
      - Video: cookbook/video.md
      - Audio: cookbook/audio.md
      - Código: cookbook/code.md
    - Desarrollando software:
      - Modelos Privados: cookbook/api.md
      - Modelos Abiertos: cookbook/integration.md
      - Tecnologías: cookbook/technologies.md

  - Glosario:
    - glossary/index.md
  - Instructores:
    - instructor/index.md